// <auto-generated />
using System;
using GestionPisosCompartidos.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPisosCompartidos.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412165635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaGasto")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ViviendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("ViviendaId");

                    b.ToTable("Gastos", t =>
                        {
                            t.HasCheckConstraint("CK_Gastos_Categoria", "Categoria IN ('Luz', 'Agua', 'Gas', 'Internet', 'Comunidad', 'Alquiler', 'Otro')");

                            t.HasCheckConstraint("CK_Gastos_ImporteTotal", "ImporteTotal > 0");
                        });
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierta");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Media");

                    b.Property<int>("ReportadaPorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViviendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportadaPorId");

                    b.HasIndex("ViviendaId");

                    b.ToTable("Incidencias", t =>
                        {
                            t.HasCheckConstraint("CK_Incidencias_Estado", "Estado IN ('Abierta', 'EnProceso', 'Resuelta', 'Cerrada')");

                            t.HasCheckConstraint("CK_Incidencias_Prioridad", "Prioridad IN ('Baja', 'Media', 'Alta', 'Urgente')");
                        });
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.InquilinosVivienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("InquilinoId")
                        .HasColumnType("int");

                    b.Property<int>("ViviendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId");

                    b.HasIndex("ViviendaId");

                    b.HasIndex("InquilinoId", "ViviendaId", "FechaInicio")
                        .IsUnique();

                    b.ToTable("InquilinosViviendas");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("GastoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("InquilinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.HasIndex("InquilinoId");

                    b.ToTable("Pagos", t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_Estado", "Estado IN ('Pendiente', 'Pagado', 'Rechazado')");

                            t.HasCheckConstraint("CK_Pagos_Importe", "Importe > 0");
                        });
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.TareasCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadaAid")
                        .HasColumnType("int")
                        .HasColumnName("AsignadaAId");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<int>("CreadaPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrecuenciaDias")
                        .HasColumnType("int");

                    b.Property<bool>("Recurrente")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViviendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignadaAid");

                    b.HasIndex("CreadaPorId");

                    b.HasIndex("ViviendaId");

                    b.ToTable("TareasCalendario", (string)null);
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Rol", "Rol IN ('Propietario', 'Inquilino')");
                        });
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Vivienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NumHabitaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PropietarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Viviendas");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Gasto", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "CreadoPor")
                        .WithMany("Gastos")
                        .HasForeignKey("CreadoPorId")
                        .IsRequired();

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Vivienda", "Vivienda")
                        .WithMany("Gastos")
                        .HasForeignKey("ViviendaId")
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Incidencia", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "ReportadaPor")
                        .WithMany("Incidencia")
                        .HasForeignKey("ReportadaPorId")
                        .IsRequired();

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Vivienda", "Vivienda")
                        .WithMany("Incidencia")
                        .HasForeignKey("ViviendaId")
                        .IsRequired();

                    b.Navigation("ReportadaPor");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.InquilinosVivienda", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "Inquilino")
                        .WithMany("InquilinosVivienda")
                        .HasForeignKey("InquilinoId")
                        .IsRequired();

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Vivienda", "Vivienda")
                        .WithMany("InquilinosVivienda")
                        .HasForeignKey("ViviendaId")
                        .IsRequired();

                    b.Navigation("Inquilino");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Pago", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Gasto", "Gasto")
                        .WithMany("Pagos")
                        .HasForeignKey("GastoId")
                        .IsRequired();

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "Inquilino")
                        .WithMany("Pagos")
                        .HasForeignKey("InquilinoId")
                        .IsRequired();

                    b.Navigation("Gasto");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.TareasCalendario", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "AsignadaA")
                        .WithMany("TareasCalendarioAsignadaAs")
                        .HasForeignKey("AsignadaAid");

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "CreadaPor")
                        .WithMany("TareasCalendarioCreadaPors")
                        .HasForeignKey("CreadaPorId")
                        .IsRequired();

                    b.HasOne("GestionPisosCompartidos.Models.Entities.Vivienda", "Vivienda")
                        .WithMany("TareasCalendarios")
                        .HasForeignKey("ViviendaId")
                        .IsRequired();

                    b.Navigation("AsignadaA");

                    b.Navigation("CreadaPor");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Vivienda", b =>
                {
                    b.HasOne("GestionPisosCompartidos.Models.Entities.Usuario", "Propietario")
                        .WithMany("Vivienda")
                        .HasForeignKey("PropietarioId")
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Gasto", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Incidencia");

                    b.Navigation("InquilinosVivienda");

                    b.Navigation("Pagos");

                    b.Navigation("TareasCalendarioAsignadaAs");

                    b.Navigation("TareasCalendarioCreadaPors");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("GestionPisosCompartidos.Models.Entities.Vivienda", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Incidencia");

                    b.Navigation("InquilinosVivienda");

                    b.Navigation("TareasCalendarios");
                });
#pragma warning restore 612, 618
        }
    }
}
